name: Trying work flow from scratch
run-name : myFirstWorkFlow
on: push

jobs:
    my-first-job:
        name: My First job
        runs-on: Ubuntu-latest
        steps:
        - name: Print Hello World frm first job
          run: echo "Hello World from my first job"

    my-second-job:
        name: My second job
        runs-on: Ubuntu-latest
        steps:
        - name: Print Hello World from second job
          run: echo "Hello World from my second job"
        needs: my-first-job
    
    my-third-job:
        name: My third job - runs a shell script
        runs-on: Ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Make hello.sh executable
          run: chmod +x MyDemoTestApplication/hello.sh
        - name: Print Hello World from third job
          run: ./MyDemoTestApplication/hello.sh
        needs: [my-first-job, my-second-job]
    my-fourth-job:
        name: My fourth job - prints secret or environment variable
        runs-on: Ubuntu-latest
        steps:
        - name: Print secret or environment variable
          env:
            MY_SECRET: "Vijay Chandran"
          run: echo "Hello $MY_SECRET from my fourth job"